#!/usr/bin/env bash

set -u

case "${1:-}" in
	"")
		exec nix build
		;;
	--test)
		exec ./test
		;;
	--debug)
		printf '%s\n' 'WAT has no separate debug build; running the complete application checks.' >&2
		exec ./test
		;;
	*)
		printf 'usage: %s [--test|--debug]\n' "$0" >&2
		exit 2
		;;
esac
