#!/usr/bin/env bash

set -u

root=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
aedicule_root=${AEDICULE_REPOSITORY:-"$root/../aedicule"}

if [[ -x "$aedicule_root/run" ]]; then
	exec "$aedicule_root/run" --watch "$root/code.wat" "$@"
fi

exec nix run --no-write-lock-file "$root#frontplane" -- \
	--watch "$root/code.wat" "$@"
