#!/usr/bin/env bash

set -u

if [[ ${VIBESTEROIDS_WAT_TEST_SHELL:-0} != 1 ]]; then
	develop=(nix develop --ignore-environment --keep HOME)
	if [[ -n ${TMPDIR:-} ]]; then
		develop+=(--keep TMPDIR)
	fi
	exec "${develop[@]}" -c env VIBESTEROIDS_WAT_TEST_SHELL=1 "$0" "$@"
fi

failures=0

run_check() {
	"$@"
	status=$?
	if (( status != 0 )); then
		failures=$((failures + 1))
	fi
}

run_check ./tests/cli/development_dependencies
run_check ./tests/cli/repository_boundary
run_check ./tests/cli/naming_conventions
run_check ./tests/cli/abi_namespace
run_check ./tests/cli/aedicule_abi_contract
run_check ./tests/cli/flake_composition
run_check ./tests/run-wast
run_check ./tests/lint-wat
run_check shellcheck build run test tests/cli/development_dependencies \
	tests/cli/repository_boundary tests/cli/naming_conventions \
	tests/cli/abi_namespace tests/cli/aedicule_abi_contract \
	tests/cli/flake_composition tests/run-wast \
	tests/lint-wat

if (( failures > 255 )); then
	exit 255
fi
exit "$failures"
